SELECT SUM(AMOUNT) FROM borrow;
SELECT SUM(AMOUNT) FROM deposit;
SELECT SUM(AMOUNT) FROM deposit WHERE BNAME='ANDHERI';
SELECT SUM(AMOUNT) FROM deposit WHERE ADATE > '1-JAN-96';
SELECT SUM(AMOUNT) FROM deposit WHERE BNAME='NAGPUR';

SELECT COUNT(*) FROM customer;
SELECT COUNT(*) FROM branch;
SELECT MAX(AMOUNT) FROM borrow WHERE `BNAME`='VRCE';
SELECT SUM(AMOUNT) FROM deposit WHERE `BNAME`='Delhi';

SELECT COUNT(DISTINCT bname) FROM CUSTOMER;
