SELECT BNAME, SUM(AMOUNT) FROM DEPOSIT GROUP BY BNAME;

SELECT B1.CITY, SUM(D1.AMOUNT)
FROM BRANCH B1, DEPOSIT D1
WHERE D1.BNAME = B1.BNAME
GROUP BY B1.CITY;

SELECT B1.CITY, SUM (D1.AMOUNT)
FROM DEPOSIT D1, BRANCH B1
WHERE D1.BNAME = B1.BNAME
GROUP BY D1.BNAME, B1.CITY;

SELECT SUM (AMOUNT)
FROM DEPOSIT
WHERE ADATE > "1996-01-01"
GROUP BY BNAME;

SELECT COUNT (DISTINCT CNAME) FROM DEPOSIT GROUP BY BNAME;

SELECT SUM(BR1.AMOUNT)
FROM BORROW BR1, CUSTOMER C1
WHERE C1.CNAME = BR1.CNAME
GROUP BY C1.CITY;