CREATE TABLE DEPOSIT (
    ACTNO VARCHAR(5),
    CNAME VARCHAR(18),
    BNAME VARCHAR(18),
    ADATE DATE
);

CREATE TABLE BRANCH (
    BNAME VARCHAR(18)
);

CREATE TABLE CUSTOMER (
    CNAME VARCHAR(19)
);

CREATE TABLE BORROW (
    LOANNO CHAR(5),
    CNAME VARCHAR(18),
    BNAME VARCHAR(18),
    AMOUNT DECIMAL(8,2)
);

ALTER TABLE DEPOSIT
    ADD COLUMN AMOUNT DECIMAL(8,2);

ALTER TABLE BRANCH 
    ADD COLUMN CITY VARCHAR(18);

ALTER TABLE BORROW 
    MODIFY COLUMN LOANNO VARCHAR(5);

ALTER TABLE DEPOSIT 
    DROP COLUMN ACTNO;

DROP TABLE BORROW;

ALTER TABLE DEPOSIT 
    RENAME SAVING;

ALTER TABLE CUSTOMER 
    RENAME EMP;