CREATE TABLE DEPOSIT (ACTNO VARCHAR(5), CNAME VARCHAR (18), BNAME VARCHAR(18), AMOUNT DECIMAL, ADATE DATE);
INSERT INTO DEPOSIT VALUES('100','ANIL','VRCE',1000.00,'1995-03-01');
INSERT INTO DEPOSIT VALUES ('101','SUNIL','AJNI ',5000.00, '1996-01-04');
INSERT INTO DEPOSIT VALUES ('102','MEHUL','KAROLBAGH',3500.00,'1995-11-17');
INSERT INTO DEPOSIT VALUES ('104','MADHURI','CHANDNI',1200.00,'1995-12-17');
INSERT INTO DEPOSIT VALUES ('105','PRAMOD','M.G.ROAD',3000.00,'1996-03-27');
INSERT INTO DEPOSIT VALUES ('106','SANDIP','ANDHERI',2000.00,'1996-03-31');
INSERT INTO DEPOSIT VALUES ('107','SHIVANI', 'VIRAR',1000.00,'1995-09-05');
INSERT INTO DEPOSIT VALUES ('108','KRANTI','NEHRU PLACE',5000.00,'1995-07-02');
INSERT INTO DEPOSIT VALUES('109','NAREN','POWAI',7000.00,'1995-08-10');
SELECT * FROM DEPOSIT;

INSERT INTO BRANCH VALUES ('VRCE','NAGPUR');
INSERT INTO BRANCH VALUES ('AJNI','NAGPUR'); 
INSERT INTO BRANCH VALUES ('KAROLBAGH','DELHI'); 
INSERT INTO BRANCH VALUES ('CHANDNII','DELHI'); 
INSERT INTO BRANCH VALUES ('DHARAMPETH','NAGPUR'); 
INSERT INTO BRANCH VALUES ('M.G.ROAD', 'BANGLORE'); 
INSERT INTO BRANCH VALUES ('ANDHERI','BOMBAY'); 
INSERT INTO BRANCH VALUES ('VIRAR','BOMBAY'); 
INSERT INTO BRANCH VALUES ('NEHRU PLACE','DELHI'); 
INSERT INTO BRANCH VALUES ('POWAI','BOMBAY');
SELECT * FROM BRANCH;

ALTER TABLE customer add COLUMN bname VARCHAR(20);
INSERT INTO CUSTOMER VALUES ('ANIL','CALCUTTA');
INSERT INTO CUSTOMER VALUES ('SUNIL','DELHI'); 
INSERT INTO CUSTOMER VALUES ('MEHUL','BARODA'); 
INSERT INTO CUSTOMER VALUES ('MANDAR','PATNA'); 
INSERT INTO CUSTOMER VALUES ('MADHURI', 'NAGPUR'); 
INSERT INTO CUSTOMER VALUES ('PRAMOD','NAGPUR'); 
INSERT INTO CUSTOMER VALUES ('SANDIP','SURAT'); 
INSERT INTO CUSTOMER VALUES ('SHIVANI','BOMBAY'); 
INSERT INTO CUSTOMER VALUES ('KRANTI','BOMBAY');
INSERT INTO CUSTOMER VALUES ('NAREN','BOMBAY'); 
SELECT * FROM CUSTOMER;

INSERT INTO BORROW VALUES ('201','ANIL','VRCE',1000.00); 
INSERT INTO BORROW VALUES ('206','MEHUL', 'AJNI',5000.00); 
INSERT INTO BORROW VALUES ('311', 'SUNIL','DHARAMPETH',3000.00); 
INSERT INTO BORROW VALUES ('321', 'MADHURI','ANDHERI',2000.00); 
INSERT INTO BORROW VALUES ('375', 'PRAMOD','VIRAR',8000.00);
INSERT INTO BORROW VALUES ('481', 'KRANTI','NEHRU PLACE', 3000.00);
SELECT * FROM BORROW;

SELECT * FROM deposit;
SELECT * FROM borrow;
SELECT * FROM customer;
SELECT * FROM branch;

SELECT ACTNO, AMOUNT FROM DEPOSIT;
SELECT CNAME, ACTNO FROM DEPOSIT;
SELECT CNAME FROM CUSTOMER;
SELECT CNAME FROM customer WHERE BNAME = 'NAGPUR';
SELECT CNAME, AMOUNT FROM DEPOSIT WHERE AMOUNT > 4000; 

	SELECT BNAME FROM BRANCH WHERE CITY = 'DELHI';

UPDATE DEPOSIT SET AMOUNT = AMOUNT*1.10;
SELECT * FROM deposit;

UPDATE DEPOSIT SET AMOUNT = AMOUNT*1.10 WHERE BNAME='VRCE';

DELETE FROM DEPOSIT WHERE CNAME='Vijay';

DELETE FROM customer WHERE bname = 'BOMBAY';
SELECT * FROM BORROW;
DELETE FROM BORROW WHERE AMOUNT > 10000;
