df = read.csv2("C:/Users/Rishabh/codes/college/IDA/datasets/bank/bank.csv", header = TRUE)
df
mean(df$age)
mean(df$balance)
median(df$age)
median(df$balance)
range(df$age)
range(df$duration)
quantile(df$age)
min(df$balance)
max(df$age)
IQR(df$balance)
var(df$age)
var(df$balance)
str(df)
df1 = data.frame(df$age, df$housing)
head(df1)
summary(df)
boxplot(df$age, df$balance)
