-- Active: 1691209649688@@127.0.0.1@3306@prac1b
ALTER TABLE deposit
MODIFY CNAME VARCHAR(255) NOT NULL,
MODIFY BNAME VARCHAR(255) NOT NULL;

ALTER TABLE deposit
MODIFY ACTNO INT UNIQUE NOT NULL;

DESC DEPOSIT;

alter table customer
add C_NO INT;

UPDATE customer
SET C_NO = '1'
WHERE CNAME="ANIL";

UPDATE customer
SET C_NO = '2'
WHERE CNAME="SUNIL";

UPDATE customer
SET C_NO = '3'
WHERE CNAME="MEHUL";

UPDATE customer
SET C_NO = '4'
WHERE CNAME="MANDAR";

UPDATE customer
SET C_NO = '5'
WHERE CNAME="MADHURI";

UPDATE customer
SET C_NO = '6'
WHERE CNAME="PRAMOD";

UPDATE customer
SET C_NO = '7'
WHERE CNAME="SANDIP";

UPDATE customer
SET C_NO = '8'
WHERE CNAME="SHIVANI";

UPDATE customer
SET C_NO = '9'
WHERE CNAME="KRANTI";

UPDATE customer
SET C_NO = '10'
WHERE CNAME="NAREN";

-- q4
ALTER TABLE Customer
ADD CONSTRAINT PRIM_CNO PRIMARY KEY (C_NO);

DESC CUSTOMER;

ALTER TABLE CUSTOMER
DROP COLUMN C_NO;

ALTER TABLE CUSTOMER
ADD PRIMARY KEY (CNAME);
ALTER TABLE CUSTOMER
ADD UNIQUE (CNAME);



ALTER TABLE deposit
ADD CONSTRAINT FOREIGN_KEY_CUSTOMER
FOREIGN KEY (CNAME) REFERENCES Customer(CNAME);

ALTER TABLE deposit
ADD CONSTRAINT Check_100 CHECK(ACTNO > 100);
DESC DEPOSIT;

ALTER TABLE DEPOSIT
MODIFY CNAME VARCHAR(250) NOT NULL;


ALTER TABLE borrow
ADD CONSTRAINT FK_CNAME 
FOREIGN KEY (CNAME) REFERENCES Customer(CNAME);
desc borrow;

ALTER TABLE borrow
DROP FOREIGN KEY FK_CNAME;

ALTER TABLE deposit
MODIFY CNAME VARCHAR(255);
