-- Active: 1691209649688@@127.0.0.1@3306@prac1b
SELECT CNAME FROM deposit
EXCEPT
SELECT CNAME FROM BORROW;

SELECT CNAME FROM deposit
INTERSECT
SELECT CNAME FROM BORROW;

SELECT D1.CNAME, D1.AMOUNT FROM DEPOSIT D1, CUSTOMER C1
WHERE C1.CITY = 'NAGPUR' AND D1.CNAME = C1.CNAME 
UNION ALL 
SELECT BR1.CNAME, BR1.AMOUNT FROM BORROW BR1, CUSTOMER C2 
WHERE C2.CITY = 'NAGPUR' AND BR1.CNAME =C2.CNAME;

